config/routes.rb
Ece495proj::Application.routes.draw do

  get "store/index"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"

  resources :products

  resources :spots do
    resources :comments
  end

  mount RailsStars::Engine => '/stars', as: :rails_stars  

  root :to => 'spots#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :spot
  attr_accessible :body, :spot_id
  
  validates :body, presence: true
  validates :spot_id, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :image_url, :price, :title
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
#
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
end

app/models/spot.rb
class Spot < ActiveRecord::Base

  has_many :comments
  attr_accessible :address, :description, :image_url, :latitude, :longitude, :title, :gmaps
  
  acts_as_gmappable

  receives_stars

  validates :title, presence: true
  validates :address, presence: true
  validates :description, presence: true

  def gmaps4rails_address
      self.address
  end

  def gmaps4rails_infowindow
      "<h1>#{title}</h1> <h4><u>Address:</u> #{address}</h4> <br></br> <th><u><b>Description:</b></u> #{description}</th> <br></br> <img src='#{image_url}' width='150' height='150'> "
  end
  
  def gmaps4rails_sidebar
     "  <th colspan='2'> <img src='#{image_url}' width='100' height='100' /> <td> #{title}</td> <br></br> </th> "
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def current_user
    @current_user ||= User.find(session[:user_id]) if
    session[:user_id]
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  # def index
    # @comments = Comment.all

    # respond_to do |format|
      # format.html # index.html.erb
      # format.json { render json: @comments }
    # end
  # end

  # GET /comments/1
  # GET /comments/1.json
  # def show
    # @comment = Comment.find(params[:id])

    # respond_to do |format|
      # format.html # show.html.erb
      # format.json { render json: @comment }
    # end
  # end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  # def edit
    # @comment = Comment.find(params[:id])
  # end

  # POST /comments
  # POST /comments.json
  def create
    @spot = Spot.find(params[:spot_id])
	@comment = @spot.comments.create!(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @spot, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  # def update
    # @comment = Comment.find(params[:id])

    # respond_to do |format|
      # if @comment.update_attributes(params[:comment])
        # format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        # format.json { head :no_content }
      # else
        # format.html { render action: "edit" }
        # format.json { render json: @comment.errors, status: :unprocessable_entity }
      # end
    # end
  # end

  # DELETE /comments/1
  # DELETE /comments/1.json
  # def destroy
    # @comment = Comment.find(params[:id])
    # @comment.destroy

    # respond_to do |format|
      # format.html { redirect_to comments_url }
      # format.json { head :no_content }
    # end
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spots }
    end
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    @spot = Spot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spot }
    end
  end

  # GET /spots/new
  # GET /spots/new.json
  def new
    @spot = Spot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spot }
    end
  end

  # GET /spots/1/edit
  def edit
    @spot = Spot.find(params[:id])
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(params[:spot])

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render json: @spot, status: :created, location: @spot }
      else
        format.html { render action: "new" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spots/1
  # PUT /spots/1.json
  def update
    @spot = Spot.find(params[:id])

    respond_to do |format|
      if @spot.update_attributes(params[:spot])
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def about
  end

  def contact
  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p><strong>
  Posted <%= time_ago_in_words(comment.created_at) %> ago
  </strong><br />
  <%= h(comment.body) %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spot_id %><br />
    <%= f.number_field :spot_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Spot</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.spot_id %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Spot:</b>
  <%= @comment.spot_id %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Made with
    <a href="http://rubyonrails.org/">Rails</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '/about' %></li>
      <li><%= link_to "Contact", '/contact' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "Project Handrail", root_path, id: "logo" %>
        <nav>
          <ul class="nav pull-right">
	<li>
   	<% if session[:user_id] != nil %>
  	    <%= link_to "#{current_user.name} (Log Out)", logout_path %>
 	  <% else %>
  	    <%= link_to "Log In", login_path %>
	   <% end %>
	</li>
            <li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Store", store_index_path %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Handrail</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body class='<%= controller.controller_name %>'>
  <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
	  <%= yield :scripts %>
	  <%= render 'layouts/footer' %>
    </div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
<% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

    <td>
      <%= image_tag(product.image_url, class: 'list_image') %>
    </td>

    <td class="list_description">
      <dl>
        <dt><%= product.title %></dt>
        <dd><%= truncate(strip_tags(product.description),
               length: 80) %></dd>
      </dl>
    </td>

    <td class="list_actions">
      <%= link_to 'Show', product %><br/>
      <%= link_to 'Edit', edit_product_path(product) %><br/>
      <%= link_to 'Destroy', product, method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/spots/_form.html.erb
<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
<!--
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
//-->
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spots/_spot.html.erb
<%= div_for @spot do %>
  <h2><%= link_to_unless_current h(@spot.title.capitalize) %></h2>
  <%= image_tag(@spot.image_url, class: 'list_image') %>
  <p><u>Address:</u></p><%= simple_format h(@spot.address) %>
  <!--
  <%= simple_format h(@spot.latitude) %>
  <%= simple_format h(@spot.longitude) %>
  //-->
  <p><u>Description:</u></p><%= sanitize(spot.description) %>
<% end %>

app/views/spots/edit.html.erb
<h1>Editing spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<h1>Listing spots</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Address</th>
	<!-- 
    <th>Image url</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Gmaps</th>
	//-->
    <th>Description</th>
    <th>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spots.each do |spot| %>
  <tr>
    <td><%= spot.title %></td>
    <td><%= spot.address %></td>
	<!-- 
    <td><%= spot.image_url %></td>
    <td><%= spot.latitude %></td>
    <td><%= spot.longitude %></td>
    <td><%= spot.gmaps %></td>
	//-->
    <td><%= sanitize(spot.description) %></td>
    <td><%= display_stars spot %></td>
    <td><%= link_to 'Show', spot %></td>
    <td><%= link_to 'Edit', edit_spot_path(spot) %></td>
    <td><%= link_to 'Destroy', spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spot', new_spot_path %>
<%= gmaps("map_options" => {"auto_adjust" => "true"},"markers" => {"data" => @json, "options" => {"list_container" => "markers_list", "randomize" => true, "max_random_distance" => 10000 } }) %>

<button class="btn btn-primary" type="button">Refresh Markers</button>
<ul id="markers_list">  </ul>

app/views/spots/new.html.erb
<h1>New spot</h1>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<%= render :partial => @spot %>

<%= link_to 'Edit', edit_spot_path(@spot) %> |
<%= link_to 'Back', spots_path %>

<h2>Difficulty Rating</h2>
<%= stars_form_for @spot %>

</br>

<h2>Comments</h2>
<!-- Add comments //-->




<%= form_for [@spot, Comment.new] do |f| %>
  <p>
    <%= f.label :body, "New Comment" %><br />
    <%= f.text_area :body, rows: 6 %>
  </p>
  <p><%= f.submit "Add Comment" %></p>
<% end %>
<!-- Show comments //-->
<div id="comments">
  <%= render partial: @spot.comments.reverse %>
</div>

app/views/static_pages/about.html.erb
<html>
<h1>About</h1>
<h3>What is Project Handrail?</h3>
<p>Project Handrail is skating and snowboarding community where users can post locations of some of there favorite locations to shred!</p><br>
<h3>What features does it have?</h3>
<p>A rating system, fully integrated Google Maps application, and a store.</p><br>
<h3>What does it cost?</h3>
<p>Nothing, thanks to cheap hardware. This site is easy to maintain.</p><br>
<h3>How did you make this awesome site?</h3>
<p>With Ruby on Rails</p>
</html>

app/views/static_pages/contact.html.erb
<html>
<h1>Contact</h1>
<h2>Comments/Questions?</h2>
<p style="text-align:center;font-size:20px">(505) 555 5847</p><br>
<p style="text-align:center;font-size:20px"><a href="mailto:siteadmin@projecthandrail.com?Subject=Question">siteadmin@projecthandrail.com</a></p>
</html>

app/views/store/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<p>
If you are interested in making a purchase, 
please email: <a href="mailto:siteadmin@projecthandrail.com?Subject=Purchase Order">siteadmin@projecthandrail.com</a>
</p>
<h1>Project Handrail Skateshop</h1>
<!-- <h2>Products Coming Soon!</h2> //-->
<!-- Products already here....kinda. Run rake db:seed to get some products in db //-->
<% @products.each do |product| %>
  <div class="entry">
    <h3><%= product.title %></h3>
    <p><%= sanitize(product.description) %></p>
	<%= image_tag(product.image_url) %>
    <div class="price_line">
      <span class="price"><%= number_to_currency(product.price) %></span>
    </div>
  </div>
  <hr>
<% end %>